# use an official node.js image as the base image

FROM node:14

#set the working directory
WORKDIR /app

#copy the package.json and install dependencies

COPY package.json  ./
RUN npm install

#copy the rest of the application
COPY . .

#Build the app
RUN npm run build 

#Expose the port the app runs on
EXPOSE 3000

CMD [ "npm", "run", "dev" ]